// <auto-generated />
using System;
using DataManagment_311.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataManagment_311.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250201083201_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Demo")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataManagment_311.EF.Entities.Basket", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("IdUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Baskets", "Demo");
                });

            modelBuilder.Entity("DataManagment_311.EF.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("IdProduct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders", "Demo");
                });

            modelBuilder.Entity("DataManagment_311.EF.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CCost")
                        .HasColumnType("int");

                    b.Property<string>("Characteristics")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Markup")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products", "Demo");
                });

            modelBuilder.Entity("DataManagment_311.EF.Entities.UserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("UserAccesses", "Demo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dae2716d-610d-415d-9bf3-dd8f58ad8d95"),
                            Dk = "12345123",
                            Login = "user1",
                            RoleId = "guest",
                            Salt = "12345",
                            UserId = new Guid("d4e7f2a5-188c-48f5-9db6-6d8999ed5e42")
                        },
                        new
                        {
                            Id = new Guid("711f2d8f-2494-4272-a667-36886035e2c8"),
                            Dk = "12345123",
                            Login = "user1-m",
                            RoleId = "moderator",
                            Salt = "12345",
                            UserId = new Guid("d4e7f2a5-188c-48f5-9db6-6d8999ed5e42")
                        },
                        new
                        {
                            Id = new Guid("e50ad259-367f-4cb9-8f0c-d9c9a462dfe5"),
                            Dk = "12345123",
                            Login = "user2",
                            RoleId = "guest",
                            Salt = "12345",
                            UserId = new Guid("14b16781-27be-4fb4-804e-803c5a98e986")
                        },
                        new
                        {
                            Id = new Guid("16f5bbf5-226b-4796-abe2-87e6fbcb0c76"),
                            Dk = "12345123",
                            Login = "user3",
                            RoleId = "guest",
                            Salt = "12345",
                            UserId = new Guid("9cab7a6a-e970-44ae-8e73-58005dce3a01")
                        },
                        new
                        {
                            Id = new Guid("94e352b6-f348-42f6-a35a-8fcbef2d4b47"),
                            Dk = "12345123",
                            Login = "user4",
                            RoleId = "guest",
                            Salt = "12345",
                            UserId = new Guid("ecf36ceb-c0d5-4107-9e02-b43f8967038e")
                        },
                        new
                        {
                            Id = new Guid("37d22e1d-4c73-4418-99b6-7a496d00780f"),
                            Dk = "12345123",
                            Login = "user4-e",
                            RoleId = "editor",
                            Salt = "12345",
                            UserId = new Guid("ecf36ceb-c0d5-4107-9e02-b43f8967038e")
                        },
                        new
                        {
                            Id = new Guid("af04f9b1-3f7f-4705-8233-9ef271cf39ef"),
                            Dk = "12345123",
                            Login = "user5",
                            RoleId = "guest",
                            Salt = "12345",
                            UserId = new Guid("449a3602-c38b-45d8-a33b-76a88085aba2")
                        },
                        new
                        {
                            Id = new Guid("89754503-2fe6-4d63-8420-3503d6d857d6"),
                            Dk = "12345123",
                            Login = "user5-a",
                            RoleId = "admin",
                            Salt = "12345",
                            UserId = new Guid("449a3602-c38b-45d8-a33b-76a88085aba2")
                        },
                        new
                        {
                            Id = new Guid("c2ae1d8c-da5d-4ea6-9458-e859f15f002a"),
                            Dk = "12345123",
                            Login = "user5-e",
                            RoleId = "editor",
                            Salt = "12345",
                            UserId = new Guid("449a3602-c38b-45d8-a33b-76a88085aba2")
                        });
                });

            modelBuilder.Entity("DataManagment_311.EF.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersData", "Demo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d4e7f2a5-188c-48f5-9db6-6d8999ed5e42"),
                            Email = "user1@i.ua",
                            Name = "user1",
                            Phone = "555-11-11"
                        },
                        new
                        {
                            Id = new Guid("14b16781-27be-4fb4-804e-803c5a98e986"),
                            Email = "user2@i.ua",
                            Name = "user2",
                            Phone = "555-11-22"
                        },
                        new
                        {
                            Id = new Guid("9cab7a6a-e970-44ae-8e73-58005dce3a01"),
                            Email = "user3@i.ua",
                            Name = "user3",
                            Phone = "555-11-33"
                        },
                        new
                        {
                            Id = new Guid("ecf36ceb-c0d5-4107-9e02-b43f8967038e"),
                            Email = "user4@i.ua",
                            Name = "user4",
                            Phone = "555-11-44"
                        },
                        new
                        {
                            Id = new Guid("449a3602-c38b-45d8-a33b-76a88085aba2"),
                            Email = "user5@i.ua",
                            Name = "user5",
                            Phone = "555-11-55"
                        });
                });

            modelBuilder.Entity("DataManagment_311.EF.Entities.UserRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CanCreate")
                        .HasColumnType("int");

                    b.Property<int>("CanDelete")
                        .HasColumnType("int");

                    b.Property<int>("CanRead")
                        .HasColumnType("int");

                    b.Property<int>("CanUpdate")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles", "Demo");

                    b.HasData(
                        new
                        {
                            Id = "guest",
                            CanCreate = 0,
                            CanDelete = 0,
                            CanRead = 0,
                            CanUpdate = 0,
                            Description = "Самостійно зареєстрований користувач"
                        },
                        new
                        {
                            Id = "editor",
                            CanCreate = 0,
                            CanDelete = 0,
                            CanRead = 1,
                            CanUpdate = 1,
                            Description = "З правом редагування контенту"
                        },
                        new
                        {
                            Id = "admin",
                            CanCreate = 1,
                            CanDelete = 1,
                            CanRead = 1,
                            CanUpdate = 1,
                            Description = "Адміністратор БД"
                        },
                        new
                        {
                            Id = "moderator",
                            CanCreate = 0,
                            CanDelete = 1,
                            CanRead = 1,
                            CanUpdate = 0,
                            Description = "З правом блокування контенту"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
